# Generated by Django 5.1.2 on 2024-11-14 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagenExtra1',
            field=models.ImageField(blank=True, null=True, upload_to='productos', verbose_name='ImágenExtra1'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagenExtra2',
            field=models.ImageField(blank=True, null=True, upload_to='productos', verbose_name='ImágenExtra2'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='foto',
            field=models.ImageField(upload_to='clientes', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(upload_to='productos', verbose_name='Imágen'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio'),
        ),
    ]
